<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CLICK_YEAR2</name>
   <tag></tag>
   <elementGuidId>7fc8e715-497e-4eee-aaac-362c0772cff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-calendar[@id='mat-datepicker-0']/mat-calendar-header/div/div/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
