<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jaikisan_logo_test</name>
   <tag></tag>
   <elementGuidId>1ab32572-4105-4b7d-86b1-828c4b68f467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='jk-brand']//*[name()='svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
