<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pan-secondname</name>
   <tag></tag>
   <elementGuidId>4b105e83-9870-4426-80c0-c5231c70af5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/section/div[2]/app-kyc-details/div/div/div[3]/mat-form-field/div/div[1]/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
