<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pan_errormessage2</name>
   <tag></tag>
   <elementGuidId>2e639e89-5c5d-4b79-817b-cbd421479f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/section/div[2]/app-kyc-details/div/div/div[3]/div[1]/mat-form-field/div/div[2]/div/mat-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
