<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsofservice_outside_test</name>
   <tag></tag>
   <elementGuidId>bb09f33c-b9ac-4cee-a44f-10210157ebd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/app-root[1]/section[1]/div[2]/app-home[1]/div[1]/div[1]/div[3]/div[1]/form[1]/div[1]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
